name: docs

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout the repository
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install doc dependencies
        run: poetry install --with docs
      - name: Build docs
        run: poetry run mkdocs build

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Deploy docs to /phomo
        run: |
          cd gh-pages
          mkdir -p phomo
          # Clear old files
          rm -rf phomo/*
          cp -r ../site/* phomo/
          # pull the CNAME back out to the root
          mv phomo/CNAME .

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Deploy docs to /phomo"
          git push origin gh-pages
